import Binary_Operations

first_number = input("Enter №1 number >>> ")
first_number = int(first_number)
print(f"Inputted value: {first_number}")
print(f"Direct code: {Binary_Operations.decimal_to_binary_direct_code(first_number)}")
print(f"Inverse code: {Binary_Operations.decimal_to_binary_inverse_code(first_number)}")
print(f"Additional code: {Binary_Operations.decimal_to_binary_additional_code(first_number)}\n")

second_number = input("Enter №2 number >>> ")
second_number = int(second_number)
print(f"Inputted value: {second_number}")
print(f"Direct code: {Binary_Operations.decimal_to_binary_direct_code(second_number)}")
print(f"Inverse code: {Binary_Operations.decimal_to_binary_inverse_code(second_number)}")
print(f"Additional code: {Binary_Operations.decimal_to_binary_additional_code(second_number)}\n")

print("Summarize:")
first_number = input("Enter №1 decimal >>> ")
first_number = int(first_number)
second_number = input("Enter №2 decimal >>> ")
second_number = int(second_number)
first_binary_additional = Binary_Operations.decimal_to_binary_additional_code(first_number)
print(f"First additional code: {first_number}")
second_binary_additional = Binary_Operations.decimal_to_binary_additional_code(second_number)
print(f"Second additional code: {second_number}")
additional_binary = Binary_Operations.additional_code_binary_sum(first_binary_additional, second_binary_additional)
print(f"Result in additional code: {additional_binary}")
decimal_result = Binary_Operations.binary_to_decimal_additional_code(additional_binary)
print(f"Decimal result: {decimal_result}\n")

print("Multiply:")
first_binary = input("Enter №1 binary >>> ")
second_binary = input("Enter №2 binary >>> ")
direct_binary = Binary_Operations.binary_multiply(first_binary, second_binary)
print(f"Result in direct code: {direct_binary}")
decimal_result = Binary_Operations.binary_to_decimal_direct_code(direct_binary)
print(f"Decimal result: {decimal_result}\n")

print("Division:")
first_decimal = input("Enter №1 decimal >>> ")
second_decimal = input("Enter №2 decimal >>> ")
other_direct_binary = Binary_Operations.binary_divide(Binary_Operations.decimal_to_binary_direct_code(int(first_decimal)),
                                                      Binary_Operations.decimal_to_binary_direct_code(int(second_decimal)))
decimal_divide_result = Binary_Operations.binary_to_decimal_division(other_direct_binary)
print(f"Binary division result: {other_direct_binary}")
print(f"Decimal division result: {decimal_divide_result}\n")

print("I-EEE754 float summarize:")
first_float = input("Enter №1 float >>> ")
second_float = input("Enter №2 float >>> ")
first_float = float(first_float)
second_float = float(second_float)
result_float, result_binary = Binary_Operations.sum_floats_ieee754(first_float, second_float)
print(f"First float in I-EEE754 format: {first_float}")
print(f"Second float in I-EEE754 format: {second_float}")
print(f"Result in binary form: {result_binary}")
print(f"Result of float sum: {result_float}")
